# dependencies - ideal as one "pip install" available
# fetchart: pip install requests
# lastgenre: pip install pylast
# embedart:
#  OS X: sudo port install ImageMagick

# directory and library should be in seperate files, if possible, see #6
# for the time being we have to switch

### choose wisely ###
# @zabelhaft
# directory: ~/beets/bib
# library: ~/beets/lib/musiclibrary.blb

# @Schweinepriester
# directory: F:\Audio\Mediathek\Musik
# directory: E:\beets\test_mediafolder
# library: E:\beets\musiclibrary.db

### start actual config ###
plugins: fetchart lastgenre embedart zero inline
paths:
    default: $albumartist/$album%aunique{}/%if{$multidisc,CD$disc/}$track $title
import:
    copy: yes # default
    write: yes # default
    resume: ask # default
    quiet_fallback: skip # default
    timid: no # default
    log: beetslog.txt
fetchart: 
    auto: yes # default
    minwidth: 750
    maxwidth: 1500
    enforce_ratio: yes
    remote_priority: yes
    sources: coverart itunes albumart amazon google wikipedia #default
zero:
    fields: comments
embedart:
    auto: yes # default
album_fields:
    bitrate: |
        total = 0
        for item in items:
            total += item.bitrate
        bitrate = total / len(items)
        return str(bitrate)[:3]
item_fields:
    multidisc: 1 if disctotal > 1 else 0
