# dependencies - ideal as one "pip install" available
# fetchart, lyrics : pip install requests
# lastgenre: pip install pylast
# discogs: pip install discogs-client #user account needed
# embedart:
#  OS X: sudo port install ImageMagick

### replace ###
#directory: @directory@
#library: @library@

### start actual config ###
plugins: fetchart lastgenre embedart zero inline lyrics ftintitle discogs fromfilename
paths:
    default: $albumartist/$album%aunique{}/%if{$multidisc,CD$disc/}$albumartist - $album%aunique{} - $track $title
replace:
    '[\\/]': _ #default
    '^\.': ''
    '[\x00-\x1f]': _ #default
    '[<>:"\?\*\|]': _ #default
    '\.$': _ #default
    '\s+$': '' #default
    '^\s+': '' #default
import:
    copy: yes # default
    write: yes # default
    resume: ask # default
    quiet_fallback: skip # default
    timid: no # default
    log: beetslog.txt
fetchart: 
    auto: yes # default
    minwidth: 750
    maxwidth: 1500
    enforce_ratio: yes
    remote_priority: yes
    sources: coverart itunes albumart amazon google wikipedia #default
zero:
    fields: comments
embedart:
    auto: yes # default
lyrics:
    auto: yes # default
    force: yes
    #google_API_key: @google_API_key@
album_fields:
    bitrate: |
        total = 0
        for item in items:
            total += item.bitrate
        bitrate = total / len(items)
        return str(bitrate)[:3]
format_album: 'Musik: $albumartist - $album ($genre - $year) @ $bitrate kBit/s'
per_disc_numbering: yes
item_fields:
    multidisc: 1 if disctotal > 1 else 0
