directory: ~/beets/bib
library: ~/beets/lib/musiclibrary.blb
plugins: fetchart lastgenre embedart zero inline
import:
    copy: yes
    write: yes
    resume: ask
    quiet_fallback: skip
    timid: no
    log: beetslog.txt
fetchart: 
    auto: yes
    minwidth: 750 
    maxwidth: 1500
    enforce_ratio: yes
zero:
    fields: comments
embedart:
    auto: yes
album_fields:
    bitrate: |
        total = 0
        for item in items:
            total += item.bitrate
        return total / len(items)

## dependencies
## fetchart: pip install requests
## lastgenre: pip install pylast
## embedart: sudo port install ImageMagick
