# directory and library should be in seperate files, if possible, see #6
# for the time being we have to switch i guess
 
# @zabelhaft
# directory: ~/beets/bib
# library: ~/beets/lib/musiclibrary.blb

# @Schweinepriester
# directory: F:\Audio\Mediathek\Musik
directory: E:\beets\test_mediafolder
library: E:\beets\musiclibrary.db

### start identical config ###
plugins: fetchart lastgenre embedart zero inline
import:
    copy: yes # default
    write: yes # default
    resume: ask # default
    quiet_fallback: skip # default
    timid: no # default
    log: beetslog.txt
fetchart: 
    auto: yes # default
    minwidth: 750
    maxwidth: 1500
    enforce_ratio: yes
zero:
    fields: comments
embedart:
    auto: yes # default
album_fields:
    bitrate: |
        total = 0
        for item in items:
            total += item.bitrate
        return total / len(items)

# dependencies - should be mentioned on top and ideal as one "pip install" available
# fetchart: pip install requests
# lastgenre: pip install pylast
# embedart: sudo port install ImageMagick
